version: '3'
services: 
  express-app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:errison2345@db:5432/mydatabase"
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma db push &&
        npm start
      "
  db: 
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: errison2345
      POSTGRES_DB: mydatabase