FROM node:19.5.0-alpine

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

RUN yarn global add prisma

RUN npx prisma generate

COPY prisma/schema.prisma ./prisma/

EXPOSE 3000

CMD ["yarn","start"]
